# Generated by Django 2.1.5 on 2019-01-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190109_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='codename',
        ),
    ]
