# Generated by Django 2.1.5 on 2019-01-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ticket_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='codename',
            field=models.CharField(default='INC-001', max_length=255, verbose_name='Referencia'),
            preserve_default=False,
        ),
    ]
