# Generated by Django 2.1.5 on 2019-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('assigned', 'Asignado'), ('in-progress', 'En proceso'), ('solved', 'Resuelto')], default='new', max_length=255, verbose_name='Estado'),
        ),
    ]
