# Generated by Django 2.1.5 on 2019-01-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190110_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('middle', 'Media'), ('high', 'Alta'), ('severe', 'Grave'), ('critical', 'Crítica')], default='low', max_length=255, verbose_name='Prioridad'),
        ),
    ]
